import Head from 'next/head'
import Banner from '../components/Banner'
import BannerImage from '../assets/banner/homepage.jpg'
import AboutUs from '../components/AboutUs'
import OurPlants from '../components/OurPlants'
import Media from '../components/Media'
import SocialMedia from '../components/SocialMedia'

export default function Home() {
  return (
    <div>
      <Head>
        <title>JSLL | Lifestyle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner src={BannerImage} text="CRAFTING A SMART FUTURE FOR A BEAUTIFUL LIVING"/>
      <AboutUs />
      <OurPlants/>
      <Media />
      <SocialMedia/>
    </div>
  )
}
