import Head from 'next/head'
import Banner from '../components/Banner'
import BannerImage from '../public/banner/homepage.jpg'
import AboutUs from '../components/AboutUs'
import OurPlants from '../components/OurPlants'
import Media from '../components/Media'
import SocialMedia from '../components/SocialMedia'
import OurBusinesses from '../components/OurBusinesses'
import BannerCarousel from '../components/BannerCarousel'
import { homePageBanners } from '../Data'

export default function Home({verticals, ModalToggle, UpdateName, UpdateFile, UpdateType }) {
  return (
    <>
      <Head>
        <title>JSLL | Lifestyle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Banner src={BannerImage} text="CRAFTING A SMART FUTURE FOR A BEAUTIFUL LIVING"/> */}
      <BannerCarousel data={homePageBanners}/>
      <AboutUs />
      <OurBusinesses data={verticals} ModalToggle={ModalToggle} UpdateFile={UpdateFile} UpdateName={UpdateName} UpdateType={UpdateType}/>
      <OurPlants/>
      <Media />
      <SocialMedia/>
    </>
  )
}


export async function getStaticProps() {
  const baseURL = process.env.API_URL;
  let data;
  try {
      const res = await fetch(baseURL + 'brochures');
      data = await res.json();
  } catch (error) {
      console.log("Server Error Occured");
  }

  return {
      props: {
          verticals: data,
      }
  }
}